### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by xjshi** [RealUserMonitoring/OpenRUM-specification#3]
1. device.hardware.ram、device.hardware.rom 未明确单位；
2. device.status.cpu.app_usage 此类表示占用百分比的，可以转为整数传输，避免精度问题；
3. 文档中“现场属性”超链接无法跳转；
4. 未明确系统 build 号，影响堆栈解析；

**Comment by yuanyaohui** [comment]
采纳；

**Comment by Bonree** [comment]
#4
